[font]
size = 12.0

[font.normal]
family = "JetBrainsMonoNerdFontMono"
style = "Regular"

[window]
padding = {x=12, y=12}
opacity = 0.9

[colors.primary]
foreground = "#c0cbec"
background = "#1C252E"
